text_extensions: [ 'css', 'erb', 'haml', 'htm', 'html', 'js', 'less', 'markdown', 'md', 'php', 'rb', 'sass', 'scss', 'txt', 'xhtml', 'xml' ]
output_dir: output
index_filenames: [ 'index.html' ]
enable_output_diff: false
data_sources:
  -
    type: filesystem_unified
    items_root: /
    layouts_root: /
title: Cameron Spickert's Blog
author_name: Cameron Spickert
author_uri: http://cameronspickert.com
base_url: http://cameronspickert.com
deploy:
  default:
    dst_remote: origin
    dst_branch: master
    src_branch: source
